project:
  type: website
  output-dir: docs

website:
  title: "Grace Rinehart"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
      - href: resume.qmd
  page-footer: 
    background: light #
    left: Copyright 2025, Grace Rinehart
    right: This website is built with Github, R, and Quarto
  
format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full

editor: visual

